version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: python_app
    environment:
      - DATABASE_HOST=DATABASE_HOST
      - DATABASE_NAME=DATABASE_NAME
      - DATABASE_USER=DATABASE_USER
      - DATABASE_PASSWORD=DATABASE_PASS
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["csv_file.csv", "table_name"]

volumes:
  postgres_data:
