apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  db_user: base64_encoded_user
  db_pass: base64_encoded_password
  db_name: base64_encoded_db_name


# echo -n 'your_user' | base64
# echo -n 'your_password' | base64
# echo -n 'your_database' | base64
